--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ParoxityTeam/ParoxityEcon
build-by-default: true
branches:
- master
projects:
  ParoxityEcon:
    path: ""
    libs:
    - src: ParoxityTeam/Commando/Commando
      version: ^0.6
    - src: poggit/libasynql/libasynql
      version: ^3.3.0
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^1.0.0
    lint:
      phpstan: false
...
