name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: wget virions, libasynql
        uses: wei/wget@v1
        with:
          args: -O vendor/libasynql.phar https://poggit.pmmp.io/r/70846/libasynql_dev-113.phar
      - name: wget virions, Commando
        uses: wei/wget@v1
        with:
          args: -O vendor/Commando.phar https://poggit.pmmp.io/r/89664/Commando_dev-18.phar
      - name: wget virions, pmforms
        uses: wei/wget@v1
        with:
          args: -O vendor/pmforms.phar https://poggit.pmmp.io/r/55533/pmforms_dev-4.phar
      - name: wget virions, await-generator
        uses: wei/wget@v1
        with:
          args: -O vendor/await-generator.phar https://poggit.pmmp.io/r/87185/await-generator_dev-39.phar
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist